### ISSUE TITLE
ERROR    [golem_sci.implementation           ] {'code': -32000, 'message': 'filter not found'} 

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#2087] opened 2018-02-12 10:59 UTC
Mac, source version, 

```ERROR    [golem_sci.implementation           ] {'code': -32000, 'message': 'filter not found'} ```

**Comment by Krigpl** [comment] 2018-02-13 10:28
Root cause described here: https://github.com/golemfactory/golem-smart-contracts-interface/issues/5
Closing this one in favor of the above.

**Closed as completed by Krigpl** 2018-02-13 10:28 UTC
Labels: bug, macos
