### ISSUE TITLE
Error starting docker. OS X 10.11.6, Golem 0.11.0

### ISSUE THREAD

**Issue by sdrpa** [golemfactory/clay#1977] opened 2018-01-26 14:06 UTC
When I start golem I get the message "Golem is starting" followed by "Docker is starting" the it ends up with "Error starting docker"
OS X 10.11.6

```
golemapp --monitor

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO     [golem.version                      ] GOLEM Version: 0.11.0 
INFO     [golem.version                      ] Protocol Version: 20 
INFO     [golem.version                      ] golem_messages Version: 1.5.1 
Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 1129, in __lock_datadir
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/tools/filelock.py", line 40, in lock
BlockingIOError: [Errno 35] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golemapp.py", line 156, in <module>
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 722, in __call__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 697, in main
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 895, in invoke
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/.venv/lib/python3.6/site-packages/click/core.py", line 535, in invoke
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golemapp.py", line 106, in start
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/node.py", line 32, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 101, in __init__
  File "/Users/buildbot-worker/worker/buildpackage_macOS/build/golem/client.py", line 1132, in __lock_datadir
OSError: Data dir /Users/sdrpa/Library/Application Support/golem/default used by other Golem instance
[29166] Failed to execute script golemapp
```

~/.golem folder is empty and is owned by user
```
drwxr-xr-x    2 sdrpa  staff     68 Jan 26 14:48 .golem
```

I tried:

```
docker-machine rm golem
docker-machine create --driver xhyve golem

Running pre-create checks...
Creating machine...
(golem) Default Boot2Docker ISO is out-of-date, downloading the latest release...
(golem) Latest release for github.com/boot2docker/boot2docker is v18.01.0-ce
(golem) Downloading /Users/sdrpa/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v18.01.0-ce/boot2docker.iso...
(golem) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
(golem) Copying /Users/sdrpa/.docker/machine/cache/boot2docker.iso to /Users/sdrpa/.docker/machine/machines/golem/boot2docker.iso...
(golem) Creating VM...
(golem) /dev/disk8                                             /Users/sdrpa/.docker/machine/machines/golem/b2d-image
(golem) "disk8" unmounted.
(golem) "disk8" ejected.
(golem) Generating 20000MB disk image...
(golem) created: /Users/sdrpa/.docker/machine/machines/golem/root-volume.sparsebundle
(golem) Creating SSH key...
(golem) Fix file permission...
(golem) Generate UUID...
(golem) Convert UUID to MAC address...
Error creating machine: Error in driver during machine creation: Could not convert the UUID to MAC address: exit status 1
```

**Comment by maaktweluit** [comment] 2018-01-26 14:42
hey @sdrpa 

Thank you for the report!
The first error indicates another golemapp is still running. This can be caused by `Golem.app`. If you want to configure `golemapp` with arguments you have to start it before `Golem.app` and it will connect automatically

The second error is new to me, to check, did you configure `xhyve` with the 2 sudo commands after installation ( [found on readme under Installation](https://github.com/golemfactory/homebrew-golem) )

**Comment by sdrpa** [comment] 2018-01-26 16:36
Seems that it works started from the command line (when I exit GUI app):

```
golemapp --monitor

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO     [golem.version                      ] GOLEM Version: 0.11.0 
INFO     [golem.version                      ] Protocol Version: 20 
INFO     [golem.version                      ] golem_messages Version: 1.5.1 
INFO     [golem.pay                          ] Node Ethereum address: 0x50704b096b947b5334cf8fb2c5911a62d700f032 
ERROR    [golem.ethereum                     ] Error downloading node list: Expecting value: line 1 column 1 (char 0) 
INFO     [golem.ethereum                     ] GETH: connecting to remote RPC interface at http://94.23.57.58:55555 
INFO     [golem.ethereum                     ] rinkeby chain (0x6341fd3daf94b748c72ced5a5b26028f2474f5f00d824504e4fa37a75767e177) 
INFO     [golem.ethereum                     ] Connected to node in 0.14817285537719727s 
INFO     [twisted                            ] No extra node router roles 
INFO     [twisted                            ] RouterServiceSession ready [no on_ready configured] 
INFO     [twisted                            ] Registered 20 procedures 
INFO     [twisted                            ] Using node shutdown triggers ['shutdown_on_shutdown_requested'] from configuration 
INFO     [twisted                            ] Configuring node from local configuration ... 
INFO     [twisted                            ] Starting 1 workers ... 
INFO     [twisted                            ] Router worker "worker-001" starting .. 
INFO     [twisted                            ] Failed to import scrypt. This is not a fatal error but does 
INFO     [twisted                            ] mean that you cannot create or decrypt privkey jsons that use 
INFO     [twisted                            ] scrypt 
INFO     [twisted                            ] CROSSBAR_RICH_LOGGING_ENABLE=True 
INFO     [twisted                            ] {"worker_title": "Router", "klass": "crossbar.worker.router.RouterWorkerSession", "node_id": "None", "worker_id": "worker-001", "pid": 29927, "python": "CPython", "reactor": "KQueueReactor", "log_time": 1516984420.031459, "level": "info", "namespace": "crossbar.worker.process.run", "text": "Started Router worker \"worker-001\" on node \"None\" [crossbar.worker.router.RouterWorkerSession / CPython-KQueueReactor]"} 
INFO     [twisted                            ] {"worker_id": "worker-001", "session_id": 1671187387461488, "log_time": 1516984420.062103, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "Router worker \"worker-001\" session 1671187387461488 initializing .."} 
INFO     [twisted                            ] {"len_reg": 39, "log_time": 1516984420.099169, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "Registered 39 procedures"} 
INFO     [twisted                            ] {"worker_id": "worker-001", "log_time": 1516984420.1003551, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "Router worker \"worker-001\" session ready"} 
INFO     [twisted                            ] Router worker "worker-001" process 29926 started 
INFO     [twisted                            ] {"log_time": 1516984420.1225631, "level": "info", "namespace": "crossbar.router.service.RouterServiceSession", "text": "RouterServiceSession ready [configured on_ready fired]"} 
INFO     [twisted                            ] {"realm": "golem", "log_time": 1516984420.123698, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "Realm 'golem' started"} 
INFO     [twisted                            ] Router "worker-001": realm 'realm-001' (named 'golem') started 
INFO     [twisted                            ] {"realm_id": "realm-001", "role_id": "role-001", "role_config": {"name": "anonymous", "permissions": [{"uri": "*", "allow": {"call": true, "register": true, "publish": true, "subscribe": true}}]}, "log_time": 1516984420.126637, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "role role-001 on realm realm-001 started"} 
INFO     [twisted                            ] Router "worker-001": role 'role-001' (named 'anonymous') started on realm 'realm-001' 
INFO     [twisted                            ] {"system": "-", "message": ["WampWebSocketServerFactory starting on 61000"], "time": 1516984420.1420329, "isError": 0, "log_time": 1516984420.1420329, "log_text": "WampWebSocketServerFactory starting on 61000", "level": "info", "namespace": "log_legacy", "text": "WampWebSocketServerFactory starting on 61000"} 
INFO     [twisted                            ] Router "worker-001": transport 'transport-001' started 
INFO     [twisted                            ] Local node configuration applied successfully! 
INFO     [twisted                            ] Starting factory <autobahn.twisted.websocket.WampWebSocketClientFactory object at 0x110883748> 
INFO     [twisted                            ] {"session_id": 3207290235710544, "realm": "golem", "log_time": 1516984420.165868, "level": "info", "namespace": "crossbar.router.router.Router", "text": "session \"3207290235710544\" joined realm \"golem\""} 
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] Peer count: 25 
INFO     [golem.pay                          ] Synchronized! 
INFO     [golem.pay                          ] ETH: 0.02886778 
INFO     [golem.token                        ] TestGNT: 1000.0 GNTW: 0.0 
```

But GUI app gives "Golem is starting" -> "Docker is starting" -> "Error starting docker"
I did both:

```
sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
```

Also:

```
brew link docker-machine
Warning: Already linked: /usr/local/Cellar/docker-machine/0.13.0
```

**Comment by sdrpa** [comment] 2018-01-26 17:01
I tried:
```
docker-machine start golem
Starting "golem"...
(golem) Waiting for VM to come online...
(golem) Waiting on a pseudo-terminal to be ready... vmx_init: processor not supported by Hypervisor.framework
Machine didn't return an IP after 120 seconds, aborting
```
Machine is iMac 2.66 GHz Intel Core 2 Duo, 8 GB 1067 MHz DDR3
Seems that it doesn't satisfy min. requirements...

**Comment by maaktweluit** [comment] 2018-01-29 13:35
We use `xhyve` as docker machine hypervisor, so we are dependent on its minimum system requirements.

For example on Windows this is VirtualBox, and requires certain HyperV and Bios settings to be working. 

Maybe on mac there are similar bios/OSs setting to enable this. Reading some quick google results on `vmx_init: processor not supported by Hypervisor.framework` there are some things to try, and some hardware limitations. Please be careful applying changes in the bios, use at own risk.
Let us know if you have any more questions or issues, you can also join the discussion on chat.golem.network and get answers there.

Closing due to found root cause: `processor not supported by Hypervisor.framework `

**Closed as completed by maaktweluit** 2018-01-29 13:35 UTC
