### ISSUE TITLE
Resource manager: error downloading

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1631] opened 2017-11-08 01:01 UTC
```
ERROR    [golem.resource.base.resourcesmanager] Resource manager: error downloading /Users/kennethascheri/Library/Application Support/golem/default/res/nonce/tmp/. (d95d9b3356726ecc68ac3e73fd45c8ab0d1c091cf3b3b9f03b13054df8adfa18): [Failure instance: Traceback: <class 'requests.exceptions.ConnectionError'>: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:916:_bootstrap_inner
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py:864:run
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_threadworker.py:46:work
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
/Users/golem/Desktop/golem/golem/network/hyperdrive/client.py:75:get_file
/Users/golem/Desktop/golem/golem/network/hyperdrive/client.py:98:_request
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/api.py:110:post
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/api.py:56:request
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/sessions.py:488:request
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/sessions.py:609:send
/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/requests/adapters.py:473:send
]
ERROR    [golem.resources                    ] Resource handshake error ('99fd6aaf7eb342900d2b46d173242526c7847645232906a6fa8e94f7e085cefad3fb3904efd9892cfe03eb64afb8f52914a6c55745ef41aaf62fb4800e6e1903'): <twisted.python.failure.Failure requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))>
INFO     [golem.pay                          ] Peer count: 25
```

**Comment by badb** [comment] 2018-02-15 20:27
Duplicate of: https://github.com/golemfactory/golem/issues/1640

**Closed as completed by badb** 2018-02-15 20:27 UTC
Labels: duplicate
