### ISSUE TITLE
preview FileNotFoundError

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#4801] opened 2019-10-16 15:07 UTC
## Description

**Golem Version**: 0.21.0

**Golem-Messages version** (leave empty if unsure): 3.11.0

**Electron version** (if used): 0.2.3

**OS** [e.g. Windows 10 Pro]:Any

**Branch** (if launched from source): -

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

During requesting a task DiscBoyBlender  error appeared in `golem.log`
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/519c058a-f018-11e9-856e-5ad86f3605c2/tmp/current_task_preview1.PNG_tmp.png' -> '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/519c058a-f018-11e9-856e-5ad86f3605c2/tmp/current_task_preview1.PNG'
```

Might be related, RPC was failing at that time. 

**Actual result**:

Golem might have problem with finishing subtasks/task.

**Screenshots**:

_If applicable, add screenshots to help explain your problem._

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the Golem
2. Start a task at least with 40 subtasks. In This case, DiscBoyBlender, resolution and samples from file, frames 40-69, 60 subtasks , 2h for a task, 20 min for subtask, bid 0.1
3. Open console for electron - toggle developer tools in Golem view menu, watch for errors.
4.Check logs for  error.

## Logs and any additional context

```
ERROR    [golem.task.taskserver              ] TaskServer.sync_network job <bound method TaskServer.__remove_old_tasks of <golem.task.taskserver.TaskServer object at 0x7f7dc9672128>> failed
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 285, in sync_network
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskserver.py", line 1108, in __remove_old_tasks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskmanager.py", line 913, in check_timeouts
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/core/common.py", line 178, in func_wrapper
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 150, in computation_failed
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 349, in _update_frame_task_preview
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 457, in __mark_sub_frame
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 364, in _open_frame_preview
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/resources/imgrepr.py", line 112, in from_image_file
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/resources/imgrepr.py", line 87, in load_from_file
apps.rendering.resources.imgrepr.OpenCVError: cv2 read image "/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/519c058a-f018-11e9-856e-5ad86f3605c2/tmp/current_task_preview27.PNG" as None
INFO     [golem.network.transport.session    ] Sending disconnect message. reason=NoMoreMessages, address=82.64.95.217:58648
INFO     [golem.network.transport.tcpserver  ] Connecting to peer. node='FB_3661'(756642af..1f57daad), adresses=['181.171.22.82:40103']
INFO     [golem.network.transport.tcpserver  ] Connecting to peer. node='Liesse'(d28760e7..64979032), adresses=['82.64.95.217:40103']
INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s)
WARNING  [golem.rpc.session                  ] RPC: Cannot publish 'evt.comp.subtask.status', session is not yet established
INFO     [golem.task.tasksession             ] Subtask assigned. task_id='519c058a-f018-11e9-856e-5ad86f3605c2', node='5f21cd5b..05727362', subtask_id='4cde8102-f020-11e9-8bee-5ad86f3605c2'
INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s)
WARNING  [golem.rpc.session                  ] RPC: Cannot publish 'evt.comp.subtask.status', session is not yet established
INFO     [golem.task.tasksession             ] Subtask assigned. task_id='519c058a-f018-11e9-856e-5ad86f3605c2', node='33e9149c..be64225a', subtask_id='612e2b9a-f020-11e9-b1c8-5ad86f3605c2'
INFO     [golem.task.tasksession             ] Offer confirmed, assigning subtask(s)
WARNING  [golem.rpc.session                  ] RPC: Cannot publish 'evt.comp.subtask.status', session is not yet established
INFO     [golem.task.tasksession             ] Subtask assigned. task_id='519c058a-f018-11e9-856e-5ad86f3605c2', node='37f494d2..f80b42ce', subtask_id='756f03e8-f020-11e9-b7ff-5ad86f3605c2'
Unhandled error in Deferred:
CRITICAL [twisted                            ] Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 405, in _offer_chosen
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    
--- <exception caught here> ---
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 405, in _offer_chosen
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 493, in _get_next_ctd
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskmanager.py", line 472, in get_next_subtask
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/blender/task/blenderrendertask.py", line 433, in query_extra_data
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 353, in _update_frame_task_preview
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 459, in __mark_sub_frame
    
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/resources/imgrepr.py", line 148, in save_with_extension
    
builtins.FileNotFoundError: [Errno 2] No such file or directory: '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/519c058a-f018-11e9-856e-5ad86f3605c2/tmp/current_task_preview27.PNG_tmp.png' -> '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/519c058a-f018-11e9-856e-5ad86f3605c2/tmp/current_task_preview27.PNG'

CRITICAL [twisted                            ] 
Traceback (most recent call last):
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 405, in _offer_chosen
  File "/home/buildbot-worker/worker/buildpackage_linux/build/.venv/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/tasksession.py", line 493, in _get_next_ctd
  File "/home/buildbot-worker/worker/buildpackage_linux/build/golem/task/taskmanager.py", line 472, in get_next_subtask
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/blender/task/blenderrendertask.py", line 433, in query_extra_data
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 353, in _update_frame_task_preview
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/task/framerenderingtask.py", line 459, in __mark_sub_frame
  File "/home/buildbot-worker/worker/buildpackage_linux/build/apps/rendering/resources/imgrepr.py", line 148, in save_with_extension
FileNotFoundError: [Errno 2] No such file or directory: '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/519c058a-f018-11e9-856e-5ad86f3605c2/tmp/current_task_preview27.PNG_tmp.png' -> '/home/ederenn/.local/share/golem/default/mainnet/ComputerRes/519c058a-f018-11e9-856e-5ad86f3605c2/tmp/current_task_preview27.PNG'
```

From console window for electron:
```
main.bundle.js:1 SAGA > HANDLER Fetch comp.task.rendering.task_fragments failed! wamp.error.no_such_procedure 
{}
 no callee registered for procedure <comp.task.rendering.task_fragments>
main.bundle.js:1 SAGA > HANDLER Fetch comp.task.rendering.task_fragments failed! wamp.error.no_such_procedure 
{}
 no callee registered for procedure <comp.task.rendering.task_fragments>
main.bundle.js:1 SAGA > HANDLER Fetch comp.task.rendering.task_fragments failed! wamp.error.no_such_procedure 
{}
 no callee registered for procedure <comp.task.rendering.task_fragments>
main.bundle.js:1 SAGA > HANDLER Fetch pay.operations failed! wamp.error.no_such_procedure 
{}
 no callee registered for procedure <pay.operations>
```

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment] 2019-10-23 08:35
@ederenn I couldn't reproduce this. But I made this PR that should handle the error better: #4823
edit: and this: #4844

**Comment by etam** [comment] 2019-11-22 10:38
I'm closing this. We can't get why images are missing, but if that happens, it should be handled properly.
Don't hesitate to reopen if there's more data or it becomes more urgent.

**Closed as completed by etam** 2019-11-22 10:38 UTC
Labels: bug, P2, 0.21 release
