### ISSUE TITLE
unable to install on deb9.1 x64

### ISSUE THREAD

**Issue by ghost** [golemfactory/clay#1719] opened 2017-12-02 11:23 UTC
this is the log file:

```


user@debian:~/golem$ ./install.sh
Docker not found. Do you want to install it? (y/n) y


INSTALLING GOLEM DEPENDENCIES



INSTALLING DOCKER

OK


Installing HyperG

W: The repository 'https://download.docker.com/linux/ubuntu stretch Release' does not have a Release file.
E: Failed to fetch https://download.docker.com/linux/ubuntu/dists/stretch/stable/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.




Docker installed successfully



Done installing Golem dependencies



Installing Golem



Downloading Golem package

./install.sh: line 198: /tmp/golem-linux.tar.gz: Permission denied


Downloading ui package (it may take awhile)

Same version of Golem () detected. Do you want to reinstall Golem? (y/n) y


Installing Golem into /home/user/golem



You need to restart your PC to finish installation


______________________________________________________________________________________________________________
user@debian:~$ golem
IPC Handlers created.
💻 Starting Golem...



____________________
```

then the gui pops up but it says starting golem with start golem button grayed out, What now?
- Docker hello world runs fine from terminal.
- https://bitcoin.org/en/full-node#port-forwarding enabled for all 3x ports and static ip

**Comment by maaktweluit** [comment] 2017-12-04 09:40
hey @hivemall 

Thanks for the report!

In your log there are 2 errors worth checking:
- docker install had errors
- golemapp install had errors

Seems like you checked if docker is working, so this should not be the problem.
Looking at the golem install, can you try to manually install this package?

```
# Download latest release ( replaced `/tmp/` with `~` )
wget -qO- https://github.com/golemfactory/golem/releases/download/0.9.1/golem-linux_x64-0.9.1.tar.gz > ~/golem-linux.tar.gz

# Extract it
tar -zxvf ~/golem-linux.tar.gz

# Create directory if it does not exists
[[ ! -d ~/golem ]] && mkdir -p ~/golem

# Copy files to golem directory
cp -rf ~/golem-0.9.1/* ~/golem

# Clean up archive and extracted tmp folder
rm -rf ~/golem-0.9.1/ &>/dev/null
rm ~/golem-linux.tar.gz &>/dev/null

# Setup symlinks
sudo ln -s ~/golem/golemapp /usr/local/bin/golemapp
sudo ln -s ~/golem/golemcli /usr/local/bin/golemcli
```
Please note the release numbers are hard-coded in this script. Now it is the latest but next release it needs a manual tweak.

The install script is only optimised for ubuntu at the moment, these steps should make it work for you as well.

**Comment by alx** [comment] 2017-12-12 11:43
Thanks for the help, it seems to resolve the docker issue, but I got the following issue related to libssl.

I'm not sure how to solve it, would you have an idea?

Thanks.

```
$ golemapp
Traceback (most recent call last):
  File "/Projects/golem/golemapp.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/golem/node.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/golem/client.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/golem/core/keysauth.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/golem/core/crypto.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/venv/lib/python3.5/site-packages/pyelliptic/__init__.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Projects/golem/venv/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
  File "/Projects/golem/venv/lib/python3.5/site-packages/pyelliptic/openssl.py", line 528, in <module>
  File "/Projects/golem/venv/lib/python3.5/site-packages/pyelliptic/openssl.py", line 180, in __init__
  File "/usr/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: undefined symbol: ECDH_OpenSSL

```

**Comment by maaktweluit** [comment] 2017-12-12 12:25
Great to hear it helped!

This looks like openssl has some troubles, could you check the version with `openssl version`?
On windows i remember the wrong version is 0.9.8 and the required version is 1.0.2, not sure what versions are running on deb.

**Comment by alx** [comment] 2017-12-12 12:32
Thanks for your comment, it was an issue related to a misconfiguration inside my /usr/lib/ folder.

**Comment by Vantskruv** [comment] 2018-01-05 12:19
https://github.com/yann2192/pyelliptic/issues/50

pyelliptic is deprecated and is directly (or indirectly) used in this project. This should be fixed by you either  maintain pyelliptic, or you use another OpenSSL wrapper.

I am therefore unable to test Brass Golem as I am using Debian.

**Comment by maaktweluit** [comment] 2018-01-05 13:18
Hey @Vantskruv 

You are correct, we use `pyelliptic` directly and indirectly. We are working on switching to another wrapper.

Personally i have no experience on Debian, on windows and mac it is possible to load other versions of `OpenSSL` for `golemapp` by adding it to the `PATH` or `DYLD_LIBRARY_PATH `.

Hope it helps, if not feel free to reply here or join the discussion on rocket chat on https://chat.golem.network , you can tag me on the same nickname.

**Comment by maaktweluit** [comment] 2018-01-05 13:19
@alx Closing this issue, feel free to re-open or make a new one when the issue is back.

**Closed as completed by maaktweluit** 2018-01-05 13:19 UTC
