### ISSUE TITLE
[ERR] task submission not successful, error in pyelliptic

### ISSUE THREAD

**Issue by golemUser1** [golemfactory/clay#2032] opened 2018-02-03 15:54 UTC
I tried today to submit one of my demo tasks again but it didn't get computed. (as long there is no prevention for submitting the same task twice, this is a bug)

it needed way too long in preparing, and then got stuck in waiting stage.

i scanned the logs and found some crypt errors. i will attach the complete logs.
[golem.error.log](https://github.com/golemfactory/golem/files/1691895/golem.error.log)
[hyperg.log](https://github.com/golemfactory/golem/files/1691897/hyperg.log)

i took a break after some problems with the task submission. it never worked with 0.11.0 for me.

**Comment by maaktweluit** [comment] 2018-02-05 13:11
Hey @golemUser1 

Thank you for the report!
could you also provide the `golem.log`? it can contain useful info messages surrounding the errors.

As a first step of investigation could you test where pyelleptic's base library is located?
This can be done running `where libeay32.dll` in cmd

**Comment by golemUser1** [comment] 2018-02-25 09:25
Sorry. must habe grapped the wrong file
here is a log file for you:
[golem.error.log](https://github.com/golemfactory/golem/files/1755844/golem.error.log)


C:\Users>where libeay32.dll
C:\Program Files (x86)\Intel\iCLS Client\libeay32.dll
C:\Program Files\Intel\iCLS Client\libeay32.dll
C:\Program Files\Golem\libeay32.dll
C:\Program Files\Common Files\Intel\WirelessCommon\libeay32.dll

**Comment by mfranciszkiewicz** [comment] 2018-02-25 11:09
This is a duplicate of https://github.com/golemfactory/golem-messages/issues/114 (resolved). Closing.

**Closed as completed by mfranciszkiewicz** 2018-02-25 11:09 UTC
Labels: feedback_needed
