### ISSUE TITLE
Task collector task persistence issue

### ISSUE THREAD

**Issue by mdtanrikulu** [golemfactory/clay#1684] opened 2017-11-20 16:39 UTC
After creating task and restarting golem instance, there's still tasks on the list but when I try to delete them from the list I'm getting this error;
 `WARNING  [golem.task.taskmanager             ] b'This is not my task 'f69ddd43-59c2-4a8c-9d27-383ed625e0c6''`

**Comment by maaktweluit** [comment] 2017-11-20 16:49
Duplicate of #1630

**Closed as completed** 2017-11-21 19:00 UTC
Labels: bug
