### ISSUE TITLE
Problem in reporting provider active task

### ISSUE THREAD

**Issue by prekucki** [golemfactory/clay#4300] opened 2019-05-31 16:05 UTC
## Description

golemapp from b0.20.

## Steps To Reproduce

1. Start golemapp.py
2. Wait for incomming task
3. during task processing call RPC `comp.tasks.stats`

```
$ golemcli tasks stats

__init__() missing 1 required keyword-only argument: 'outfilebasename'
```

**Comment by shadeofblue** [comment] 2019-06-10 09:59
duplicate of: https://github.com/golemfactory/golem/issues/4116

**Closed as completed by shadeofblue** 2019-06-10 09:59 UTC
