### ISSUE TITLE
golemapp app_cfg.ini became corrupt

### ISSUE THREAD

**Issue by marmistrz** [golemfactory/clay#1269] opened 2017-08-17 08:46 UTC
See this diff:
```
$ diff --unified app_cfg.ini ../../golem.old/default/app_cfg.ini 
--- app_cfg.ini	2017-08-17 10:13:28.341439260 +0200
+++ ../../golem.old/default/app_cfg.ini	2017-08-16 17:33:27.729327883 +0200
@@ -4,32 +4,32 @@
 public address = 
 eth account = 
 use ipv6 = 0
-start port = 40102
-end port = 60102
-rpc address = localhost
-rpc port = 61000
-seed host = 
+start port = 0
+end port = 0
+rpc address = 
+rpc port = 0
+seed host = 188.165.227.180
 seed port = 40102
 opt peer num = 10
 accept tasks = 1
 send pings = 1
-hardware preset name = custom
+hardware preset name = 
 min price = 500000000000000000
 max price = 5000000000000000000
 requesting trust = -1.0
 computing trust = -1.0
-estimated lux performance = 678.3282519364941
-estimated blender performance = 356.7478770518779
+estimated lux performance = 719.613046711
+estimated blender performance = 254.016093914
 pings interval = 120
 getting peers interval = 4.0
 getting tasks interval = 4.0
-task request interval = 5.0
-node snapshot interval = 10.0
-network check interval = 10.0
+task request interval = 0.0
+node snapshot interval = 0.0
+network check interval = 0.0
 max results sending delay = 360
 p2p session timeout = 240
 task session timeout = 900
-resource session timeout = 600
+resource session timeout = 0
 use waiting for task timeout = 0
 waiting for task timeout = 720
 waiting for task session timeout = 20
```
Then, when launching `golemapp`:
```
INFO     [golem.ethereum                     ] rinkeby chain (0x6341fd3daf94b748c72ced5a5b26028f2474f5f00d824504e4fa37a75767e177)
INFO     [golem.ethereum                     ] Node started in 2.800000000000001s: `/usr/bin/geth --datadir=/home/marcin/.local/share/golem/default/ethereum/rinkeby --cache=32 --syncmode=light --rinkeby --port=50403 --ipcpath=/tmp/rinkeby-50403 --nousb --verbosity 3`
Unhandled Error
Traceback (most recent call last):
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/internet/base.py", line 428, in fireEvent
    DeferredList(beforeResults).addCallback(self._continueFiring)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/internet/defer.py", line 321, in addCallback
    callbackKeywords=kw)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
    self._runCallbacks()
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
--- <exception caught here> ---
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/twisted/internet/base.py", line 441, in _continueFiring
    callable(*args, **kwargs)
  File "/home/marcin/proj/golem/golem/rpc/router.py", line 54, in _start
    self._start_node(options, reactor).addCallbacks(callback, errback)
  File "/home/marcin/proj/golem/golem/rpc/router.py", line 60, in _start_node
    checkconfig.check_config(self.config)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 2939, in check_config
    check_worker(worker)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 2805, in check_worker
    check_router(worker)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 2479, in check_router
    check_router_transport(transport)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 2056, in check_router_transport
    check_listening_transport_websocket(transport)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 1744, in check_listening_transport_websocket
    check_listening_endpoint(transport['endpoint'])
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 977, in check_listening_endpoint
    check_listening_endpoint_tcp(endpoint)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 797, in check_listening_endpoint_tcp
    check_endpoint_port(port)
  File "/home/marcin/venv3/golem/lib/python3.6/site-packages/crossbar/common/checkconfig.py", line 682, in check_endpoint_port
    raise InvalidConfigException("invalid value {} for 'port' attribute in {}".format(port, message))
crossbar.common.checkconfig.InvalidConfigException: invalid value 0 for 'port' attribute in listening/connection endpoint
```

**Comment by badb** [comment] 2017-09-18 22:20
Probably it's a duplicate of #1230. Check also PR #1323

**Closed as completed** 2017-09-18 22:20 UTC
Labels: duplicate
