### ISSUE TITLE
setting timeouts glitch

### ISSUE THREAD

**Issue by chriscrutt** [golemfactory/clay#1842] opened 2018-01-03 23:33 UTC
Bug

When I set a task/subtask timeout on my MacBook Pro, [this happens](https://i.imgur.com/UExtoXw.mp4)

Pretty much for some reason typing "1" gives a value of zero for the first number, and it continues glitchy as such.

**Comment by badb** [comment] 2018-01-04 12:13
Hi @chriscrutt!
Thanks for reporting, we'll check and fix it! 
@ederenn Can you confirm?

**Comment by mdtanrikulu** [comment] 2018-01-04 12:16
@badb Confirmed. There's a problem with maximum date normalization on used library. Working on it.

**Comment by ederenn** [comment] 2018-01-05 12:09
when typing in task timeout   XX days:
first digit in row switches to X-1, 
second to X-2 or sometimes X-1, 
in XX hours, if you type 1X or 0X it also decreases number which is currently typed in days 
for example 56days 1X hours, switches to 54days 1X hours, 
witch bigger digits range 2-9 sometimes it decreases days number, other time decreases days and hours as well
when there is 00days and you type in hours number bigger than 23, it increases days number - not exactly corresponding with what was typed

**Comment by mdtanrikulu** [comment] 2018-01-05 12:34
> first digit in row switches to X-1,
> second to X-2 or sometimes X-1,

Maximum limit of date is 2 days, that means you're permitted to write at most 
`01days 23hours 59m 59s`
 
trying to increase any of it will turn back you to the beginning (00:00:00:00) 
this part explains first and second digit behaviour

> in XX hours, if you type 1X or 0X it also decreases number which is currently typed in days
> for example 56days 1X hours, switches to 54days 1X hours,
> witch bigger digits range 2-9 sometimes it decreases days number, other time decreases days and hours as well

Current library has max. date normalization bug, so in every change if your day input bigger than maximum value (because of the bug it's possible, 56 > 02 in this case) it's trying to normalize maximum date. 
Thus, current days decreasing when you do any change in hours, min, or sec. until it reaches under the max val.

> when there is 00days and you type in hours number bigger than 23, it increases days number - not exactly corresponding with what was typed

If your hour input exceeds the hour-day limit, the library will automatically print it out on the day section. thus, days will increase. It same for minutes, seconds bigger than 59.

Current problem here is just a max. date normalization. And I already sent patch to the library repo, waiting for merge.

**Comment by ederenn** [comment] 2018-01-05 15:03
<img width="497" alt="screen shot 2018-01-05 at 3 42 31 pm" src="https://user-images.githubusercontent.com/32061891/34613851-9b5e7c1a-f22f-11e7-92ea-0b17967e5a98.png">

it is possible to start a task with this timeout set 

although, after start, in settings it switches to (and user may not know about switch, so possibility of typing in something bigger than maximum limit should be blocked)

<img width="458" alt="screen shot 2018-01-05 at 3 41 17 pm" src="https://user-images.githubusercontent.com/32061891/34614853-212ade94-f233-11e7-9d7e-5b96c8d10a56.png">

**Comment by chriscrutt** [comment] 2018-01-06 04:07
one option would be to have up/down arrows on the side (like for Subtask Amount), and allow the user to select "days" and click up or down for more or less, "hours", and so on

**Comment by mdtanrikulu** [comment] 2018-01-17 16:59
Resolved with https://github.com/golemfactory/golem-electron/commit/52cff07b1db8bf044925fa692de7c9e1ac68598a.

As an UI element, there is no up/down arrows for now,  but up/down arrows are active on keyboard.

**Closed as completed by mdtanrikulu** 2018-01-17 16:59 UTC
Labels: bug, macos
