### ISSUE TITLE
restart of a frame in finished task is not working properly

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3265] opened 2018-08-31 20:14 UTC
#### Steps to reproduce

- start a multiframe task, at least two frames, wait for task to finish
- go to second preview window (click detailed view on preview image), to frames view 
- click resubmit on chosen frame
- on task view progress bar will jump back, and subtasks within frame will change status from finished to restarted
- task will end in timeout - no nodes are starting computations 

<img width="488" alt="screen shot 2018-08-31 at 19 51 19" src="https://user-images.githubusercontent.com/32061891/44933651-285b2280-ad6a-11e8-9bc7-94b8f2158436.png">

<img width="439" alt="screen shot 2018-08-31 at 19 51 50" src="https://user-images.githubusercontent.com/32061891/44933665-35781180-ad6a-11e8-9bf2-8cda4e13510f.png">

task seems to be restarted, but task status is not changed to restarted, no other node is starting computations for restarted subtasks
only result is - change in progress bar

**Comment by etam** [comment] 2018-09-03 10:16
When creating a task, fundslocker locks funds for a given amount of subtasks. When restarting subtasks, additional funds aren't locked. While task is running, after the original amount of subtasks is finished, when next subtask is finished, this happens:

```
2018-09-03 12:09:18 INFO     golem.ethereum.fundslocker          Removing subtask lock for task 'c2627128-af60-11e8-af36-7982c4f3937b'
2018-09-03 12:09:18 CRITICAL twisted                             Unhandled Error
Traceback (most recent call last):
  File "./golemapp.py", line 188, in start
    node.start()
  File "/home/etam/code/github/golemfactory/golem/develop/golem/node.py", line 130, in start
    self._reactor.run()
  File "/home/etam/code/github/golemfactory/golem/develop/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/home/etam/code/github/golemfactory/golem/develop/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 1252, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/home/etam/code/github/golemfactory/golem/develop/venv/lib/python3.6/site-packages/twisted/internet/base.py", line 851, in runUntilCurrent
    f(*a, **kw)
  File "/home/etam/code/github/golemfactory/golem/develop/venv/lib/python3.6/site-packages/golem_verificator/blender_verifier.py", line 88, in success
    self.verification_completed()
  File "/home/etam/code/github/golemfactory/golem/develop/venv/lib/python3.6/site-packages/golem_verificator/core_verifier.py", line 40, in verification_completed
    result=self._get_answer())
  File "/home/etam/code/github/golemfactory/golem/develop/apps/blender/verification_queue.py", line 95, in callback
    entry.cb(*args, **kwargs)
  File "/home/etam/code/github/golemfactory/golem/develop/apps/core/task/coretask.py", line 210, in verification_finished
    verification_finished_()
  File "/home/etam/code/github/golemfactory/golem/develop/golem/core/common.py", line 162, in func_wrapper
    return func(*args, **kwargs)
  File "/home/etam/code/github/golemfactory/golem/develop/golem/task/taskmanager.py", line 704, in verification_finished
    verification_finished_()
  File "/home/etam/code/github/golemfactory/golem/develop/golem/task/tasksession.py", line 214, in verification_finished
    eth_address,
  File "/home/etam/code/github/golemfactory/golem/develop/golem/task/taskserver.py", line 459, in accept_result
    self.client.funds_locker.remove_subtask(task_id)
  File "/home/etam/code/github/golemfactory/golem/develop/golem/ethereum/fundslocker.py", line 102, in remove_subtask
    self.transaction_system.unlock_funds_for_payments(task_lock.price, 1)
  File "/home/etam/code/github/golemfactory/golem/develop/golem/ethereum/transactionsystem.py", line 348, in unlock_funds_for_payments
    self._gntb_locked / denoms.ether,
builtins.Exception: Can't unlock 0.16666666666666666 GNT, locked: 0.0
```

(I'm testing if it's the only cause of the problem)

**Comment by etam** [comment] 2018-09-03 11:09
Other thing: if task is finished, it's possible to click to resubmit a frame, but it's just making 
```
INFO     [golem.task.taskmanager             ] task is not active: fc52b038-af68-11e8-824a-7982c4f3937b, status: TaskStatus.finished
```
and nothing happens. UI is changing progress bar, like there was some computation left, but the task state is still "finished".

**Comment by etam** [comment] 2018-09-03 12:42
Duplicate of #2762?

**Comment by etam** [comment] 2018-09-04 14:31
https://github.com/golemfactory/golem/pull/3266#issuecomment-418136489

**Closed as completed** 2018-09-11 14:00 UTC
Labels: bug
