### ISSUE TITLE
Task initialization failure sets incorrect task state

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/clay#4850] opened 2019-11-04 15:30 UTC
## Description

If Golem task initialization fails (for example initialize function throws exception), task state will be set to _creating_ for always.

**Golem Version**:
current develop

**OS** [e.g. Windows 10 Pro]:
Ubuntu (but it shouldn't matter)

**Branch** (if launched from source):
develop

**Description of the issue**:

Golem catches exception properly, but it is handled by decorator which seems to be outdated. 
Problem occures in _task_creation_failed_ taskmanager.py line 240, where task_id parameter is set to None. This function got None, because __create_task_error_ decorator, which handles exceptions, tried to get task_id from task_dict. But task_dict doesn't have id, only task_definition does.

## Steps To Reproduce
1. Add throw statement to initialize function of any task (I tested it on transcoding use case, but should work with blender task either)
2. Request task.
3. Observe results: Golem will create task, assign id to it, but than you will see in logs: Cannot create task. task_id=None.
4. If you break somewhere with debugger you will see, that task status remained _creating_

## Expected behavior
I expect that task result will be set to _errorCreating_.

## Logs and any additional context
    INFO     [golem.task.rpc                     ] Creating task. task_dict={'type': 'FFMPEG', 'compute_on': 'cpu', 'name': 'Transcoding id 37', 'timeout': '00:30:00', 'subtask_timeout': '00:10:00', 'subtasks_count': 1, 'bid': 1, 'resources': ['/home/nieznanysprawiciel/Repos/Golem/transcoding-demo/Storage/r_25/tmp2_sptvs5'], 'options': {'output_path': '/home/nieznanysprawiciel/Repos/Golem/transcoding-demo/Storage/r_25/37', 'output_filename': 'Golem-timelapse-03-mpeg4-fullHD_1920x1080_vp9.webm', 'container': 'webm', 'video': {'resolution': [1920, 1080], 'codec': 'vp9'}}}
    INFO     [golem.task.taskmanager             ] Creating task. type=<class 'apps.transcoding.ffmpeg.task.ffmpegTask'>, id=043fed28-ff16-11e9-868b-dc2e10f8d3e6
    INFO     [golem.environments.environmentsmanager] Adding environment FFMPEG supported=<SupportStatus ok ({})>
    INFO     [golem.network.p2p.peersession      ] Starting peer session. address=94.23.196.166:40102
    INFO     [apps.transcoding.ffmpeg.utils      ] Stream /home/nieznanysprawiciel/Repos/Golem/transcoding-demo/Storage/r_25/tmp2_sptvs5 has successfully passed the extract+split operation. Segments: ['/home/nieznanysprawiciel/Data/GolemData/Requestor1/rinkeby/ComputerRes/043fed28-ff16-11e9-868b-dc2e10f8d3e6/tmp/output/tmp2_sptvs5[video-only]_0']
    ERROR    [golem.task.taskmanager             ] Cannot create task. task_id=None : Debug throw

**Comment by etam** [comment] 2019-11-28 09:36
![meme](https://user-images.githubusercontent.com/220752/69794608-df8f5500-11ca-11ea-873e-349874662be7.jpg)

**Comment by etam** [comment] 2019-11-28 14:05
this is caused by #4324

**Comment by etam** [comment] 2019-12-09 09:41
#4951 was merged to b0.22

**Closed as completed by etam** 2019-12-09 09:41 UTC
Labels: bug, important, P3
