### ISSUE TITLE
No secret for `golemcli` when flag --mainnet is missing

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#3477] opened 2018-10-19 13:22 UTC
#### Encountered on:
Linux, GOLEM Version: 0.18.0+dev34.g4147ec1

Golemapp was running on mainnet, when user wants to use golemcli and flag `--mainnet` is missing
in console error is given:

```
(golem-env) ederenn@ederenn-ubnt1804:~/projects/golem$ python golemcli.py network connect 10.30.10.95 40102
Error connecting to Golem instance (wss://localhost:61000): [Failure instance: Traceback (failure with no frames): <class 'autobahn.wamp.types.CloseDetails'>: CloseDetails(reason=<wamp.error.not_authorized>, message='WAMP-CRA signature is invalid')
]
Cannot connect to 10.30.10.95:40102: Cannot connect to Golem instance

**Comment by mplebanski** [comment] 2018-10-19 14:12
IIRC this is an expected behavior. Is it causing any problems?

**Comment by jiivan** [comment] 2018-10-19 14:36
I propose that both CLI and electron should check _other_ dir and suggest correct flag.

 1. If `--mainnet` check rinkeby directory to see if core runs there (just check if lock file exists?). If it does, then `print("Detected golem core on rinkeby. Have you tried removing --mainnet?")`
 2. If not `--mainnet` then check mainnet dir, and possibly `print("Detected golem core on mainnet. Have you tried adding --mainnet flag?")`

**Comment by jiivan** [comment] 2018-11-05 11:14
duplicate of: #3414

**Closed as completed by jiivan** 2018-11-05 11:14 UTC
Labels: bug, cli
