### ISSUE TITLE
Exception in thread Thread-3: ... sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by kascheri12** [golemfactory/clay#1708] opened 2017-11-30 07:04 UTC
Happened twice in a row starting golem.
MacOS 10.13.1 
golem-0.9.1

```
$...../golem-0.9.1/golemapp ; exit;

Failed to import scrypt. This is not a fatal error but does
mean that you cannot create or decrypt privkey jsons that use
scrypt

INFO     [golem.version                      ] GOLEM Version: 0.9.1
INFO     [golem.version                      ] P2P Protocol Version: 15
INFO     [golem.version                      ] Task Protocol Version: 16
INFO     [golem.pay                          ] Node Ethereum address: 0x23746f5ce5ad2d0764b555e99f001f7ea509a521
ERROR    [golem.ethereum                     ] Error downloading node list: Expecting value: line 1 column 1 (char 0)
INFO     [golem.ethereum                     ] GETH: connecting to remote RPC interface at http://188.165.227.180:55555
INFO     [golem.ethereum                     ] rinkeby chain (0x6341fd3daf94b748c72ced5a5b26028f2474f5f00d824504e4fa37a75767e177)
INFO     [golem.ethereum                     ] Connected to node in 0.5111241340637207s
INFO     [twisted                            ] No extra node router roles
INFO     [twisted                            ] Using default node shutdown triggers ['shutdown_on_worker_exit']
INFO     [twisted                            ] Configuring node from local configuration ...
INFO     [twisted                            ] Starting 1 workers ...
INFO     [twisted                            ] Router worker "worker-001" starting ..
INFO     [twisted                            ] Failed to import scrypt. This is not a fatal error but does
INFO     [twisted                            ] mean that you cannot create or decrypt privkey jsons that use
INFO     [twisted                            ] scrypt
INFO     [twisted                            ] CROSSBAR_RICH_LOGGING_ENABLE=True
INFO     [twisted                            ] {"worker_title": "Router", "worker_id": "worker-001", "pid": 1478, "python": "CPython", "reactor": "KQueueReactor", "log_time": 1512025127.4380329, "level": "info", "namespace": "crossbar.worker.process.run", "text": "Router worker \"worker-001\" process 1478 starting on CPython-KQueueReactor .."}
INFO     [twisted                            ] {"worker_id": "worker-001", "session_id": 7461707677060740, "log_time": 1512025127.829015, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "Router worker \"worker-001\" session 7461707677060740 initializing .."}
INFO     [twisted                            ] {"worker_id": "worker-001", "log_time": 1512025127.841255, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "Router worker \"worker-001\" session ready"}
INFO     [twisted                            ] Router worker "worker-001" process 1477 started
INFO     [twisted                            ] {"realm": "golem", "log_time": 1512025127.8454988, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "Realm 'golem' started"}
INFO     [twisted                            ] Router 'worker-001': realm 'realm-001' (named 'golem') started
INFO     [twisted                            ] {"realm_id": "realm-001", "role_id": "role-001", "role_config": {"name": "anonymous", "permissions": [{"uri": "*", "allow": {"call": true, "register": true, "publish": true, "subscribe": true}}]}, "log_time": 1512025127.846845, "level": "info", "namespace": "crossbar.worker.worker.NativeWorkerSession", "text": "role role-001 on realm realm-001 started"}
INFO     [twisted                            ] Router 'worker-001': role 'role-001' (named 'anonymous') started on realm 'realm-001'
INFO     [twisted                            ] {"system": "-", "message": ["WampWebSocketServerFactory starting on 61000"], "time": 1512025127.8508, "isError": 0, "log_time": 1512025127.8508, "log_text": "WampWebSocketServerFactory starting on 61000", "level": "info", "namespace": "log_legacy", "text": "WampWebSocketServerFactory starting on 61000"}
INFO     [twisted                            ] Router 'worker-001': transport 'transport-001' started
INFO     [twisted                            ] Local node configuration applied successfully!
INFO     [twisted                            ] {"session_id": 4369608509298806, "realm": "golem", "details": {"session": 4369608509298806, "authid": "GFWW-P6SX-WPMC-XLWK-YCU7-PSPX", "authrole": "anonymous", "authmethod": "anonymous", "authprovider": "static", "transport": {"type": "websocket", "protocol": "wamp.2.msgpack.batched", "peer": "tcp4:127.0.0.1:52945", "http_headers_received": {"user-agent": "AutobahnPython/0.18.1", "host": "127.0.0.1:61000", "upgrade": "WebSocket", "connection": "Upgrade", "pragma": "no-cache", "cache-control": "no-cache", "sec-websocket-key": "rgKKtUAxMCyogPcuvMvOUg==", "sec-websocket-protocol": "wamp.2.cbor.batched,wamp.2.cbor,wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.ubjson.batched,wamp.2.ubjson,wamp.2.json.batched,wamp.2.json", "sec-websocket-extensions": "permessage-deflate; client_no_context_takeover; client_max_window_bits", "sec-websocket-version": "13"}, "http_headers_sent": {}, "websocket_extensions_in_use": [], "cbtid": null}}, "log_time": 1512025127.86835, "level": "info", "namespace": "crossbar.router.router.Router", "text": ">>>>> session 4369608509298806 JOINED \"golem\" >>>>>\n\n{{'session': 4369608509298806, 'authid': 'GFWW-P6SX-WPMC-XLWK-YCU7-PSPX', 'authrole': 'anonymous', 'authmethod': 'anonymous', 'authprovider': 'static', 'transport': {{'type': 'websocket', 'protocol': 'wamp.2.msgpack.batched', 'peer': 'tcp4:127.0.0.1:52945', 'http_headers_received': {{'user-agent': 'AutobahnPython/0.18.1', 'host': '127.0.0.1:61000', 'upgrade': 'WebSocket', 'connection': 'Upgrade', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'sec-websocket-key': 'rgKKtUAxMCyogPcuvMvOUg==', 'sec-websocket-protocol': 'wamp.2.cbor.batched,wamp.2.cbor,wamp.2.msgpack.batched,wamp.2.msgpack,wamp.2.ubjson.batched,wamp.2.ubjson,wamp.2.json.batched,wamp.2.json', 'sec-websocket-extensions': 'permessage-deflate; client_no_context_takeover; client_max_window_bits', 'sec-websocket-version': '13'}}, 'http_headers_sent': {{}}, 'websocket_extensions_in_use': [], 'cbtid': None}}}}\n"}
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] Synchronized!
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
WARNING  [golem.docker.manager               ] Docker: pulling image golemfactory/base:1.2
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
WARNING  [golem.docker.manager               ] Docker: pulling image golemfactory/blender:1.3
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
WARNING  [golem.docker.manager               ] Docker: pulling image golemfactory/luxrender:1.2
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
ERROR    [golem.core.hostaddress             ] Can't connect to outer service: [Errno 8] nodename nor servname provided, or not known
INFO     [twisted                            ] ProtocolFactory starting on 40102
INFO     [twisted                            ] Starting factory <golem.network.transport.network.ProtocolFactory object at 0x11140dc88>
INFO     [twisted                            ] ProtocolFactory starting on 40103
INFO     [twisted                            ] Starting factory <golem.network.transport.network.ProtocolFactory object at 0x116425128>
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 3768, in execute_sql
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
  File "/Users/golem/Desktop/golem/golem/task/taskserver.py", line 456, in reward_for_subtask_paid
  File "/Users/golem/Desktop/golem/golem/transactions/ethereum/ethereumincomeskeeper.py", line 104, in received
  File "/Users/golem/Desktop/golem/golem/transactions/incomeskeeper.py", line 65, in received
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 5155, in delete_instance
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 3556, in execute
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 2912, in _execute
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 3775, in execute_sql
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 3598, in __exit__
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 135, in reraise
  File "/Users/golem/Desktop/golem/venv3/lib/python3.6/site-packages/peewee.py", line 3768, in execute_sql
peewee.OperationalError: database is locked

INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816
INFO     [golem.resources                    ] Starting resource handshake with '328f7fcfbf3da58fcacd4c88daa7de521bca1a5820d57007d653c77db280ae7832823ce90a639ea9b585a8ace3e972696441006f2ae793022fef4f76d1712949'
INFO     [golem.pay                          ] Peer count: 25
INFO     [golem.pay                          ] ETH: 0.33369088
INFO     [golem.pay                          ] GNT: 2032.9344903648816

```

**Comment by badb** [comment] 2018-02-14 17:38
Duplicate of: https://github.com/golemfactory/golem/issues/1775

**Closed as completed by badb** 2018-02-14 17:38 UTC
Labels: duplicate
