### ISSUE TITLE
Resource handshake error: reading nonce from file "[]": list index out of range

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5178] opened 2020-04-29 12:24 UTC
## Description

**Golem Version**: 0.23.0

**Golem-Messages version** (leave empty if unsure):

**Electron version** (if used):0.2.5

**OS** [e.g. Windows 10 Pro]: Ubuntu 18.04

**Branch** (if launched from source):

**Mainnet/Testnet**: mainnet 

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:

During computations of a longer task, with 20 frames, 40 subtasks error appeared in logs
```2020-04-28 15:36:32 INFO golem.resources Resource handshake error ('7a2b56d3..bd105b7e'): reading nonce from file "[]": list index out of range
2020-04-28 15:36:32 INFO golem.task.acl Banned node. node_id=7a2b56d3..bd105b7e, timeout=7200s, persist=False
```

**Actual result**:

Node was banned

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the app  0.23.0 version
2. Start a task, DiscBoyBlender frames 40-59, subtasks 40, task timeout 2,5h, subtask timeout 25 min, res and samples from file, bid 0.1, concent off
3. Check logs for error

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment] 2020-05-04 12:40
duplicate of #5059

**Closed as completed by etam** 2020-05-04 12:40 UTC
Labels: bug, P3, 0.23 release
