### ISSUE TITLE
Missing trie node error after running Golem command

### ISSUE THREAD

**Issue by JBaba** [golemfactory/clay#1086] opened 2017-05-27 20:51 UTC
I run the command `./golemapp -p 188.165.227.180:40102` its throwing the following error repetitively after getting some headers,

```
ERROR    [golem                              ] Service Error: Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    
--- <exception caught here> ---
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    
  File "/home/mfrancis/Projects/golem/golem/ethereum/paymentprocessor.py", line 311, in _run
    
  File "/home/mfrancis/Projects/golem/golem/ethereum/paymentprocessor.py", line 284, in get_ether_from_faucet
    
  File "/home/mfrancis/Projects/golem/golem/ethereum/paymentprocessor.py", line 133, in eth_balance
    
  File "/home/mfrancis/Projects/golem/golem/ethereum/client.py", line 89, in get_balance
    
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/web3/utils/functional.py", line 14, in inner
    
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/web3/eth.py", line 120, in getBalance
    
  File "/home/mfrancis/Projects/golem/venv/lib/python2.7/site-packages/web3/providers/manager.py", line 51, in request_blocking
    
exceptions.ValueError: {u'message': u'Missing trie node d223c14df16767b42422d95b2946f624bc719ef09e708954c93d18caf060aecb', u'code': -32000}
 
None

```

**Comment by zacharytamas** [comment] 2017-05-28 02:14
I was experiencing this earlier as well.

**Comment by badb** [comment] 2017-06-05 09:30
That issue can be treated as a duplicate of #1001

**Closed as completed by badb** 2017-06-05 09:30 UTC
Labels: duplicate
