### ISSUE TITLE
ValueError: Config can be updated only when the environment is disabled

### ISSUE THREAD

**Issue by ederenn** [golemfactory/clay#5151] opened 2020-03-27 14:47 UTC
## Description

**Golem Version**: 0.22.1+dev124.gf5a985e

**Golem-Messages version** (leave empty if unsure): 3.15.0

**Electron version** (if used):

**OS** [e.g. Windows 10 Pro]: Ubuntu 18.04

**Branch** (if launched from source): b0.23

**Mainnet/Testnet**: mainnet

**Priority label is set to the lowest by default. To setup higher priority please change the label**
_P0 label is set for Severity-Critical/Effort-easy
P1 label is set  for Severity-Critical/Effort-hard
P2 label is set for Severity-Low/ Effort-easy
P3 label is set for Severity-Low/Effort-hard_

**Description of the issue**:
After pausing golem thera are problems with switching on/off requesting only. In logs appears an error
```ERROR    [twisted                            ] Session.onUserError(): "ValueError: Config can be updated only when the environment is disabled"
Traceback (most recent call last):
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/ederenn/projects/golem/golem/task/taskserver.py", line 866, in _change_task_computer_config
    config_changed = yield self.task_computer.change_config(config_desc)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1613, in unwindGenerator
    return _cancellableInlineCallbacks(gen)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
    _inlineCallbacks(None, g, status)
--- <exception caught here> ---
  File "/home/ederenn/projects/golem/golem/client.py", line 1525, in activate_hw_preset
    result = yield deferred
  File "/home/ederenn/projects/golem/golem/task/taskserver.py", line 858, in change_config
    yield self._change_task_computer_config(config_desc, run_benchmarks)
  File "/home/ederenn/projects/golem/golem/task/taskserver.py", line 866, in _change_task_computer_config
    config_changed = yield self.task_computer.change_config(config_desc)
  File "/home/ederenn/projects/golem-env/lib/python3.6/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "/home/ederenn/projects/golem/golem/task/taskcomputer.py", line 263, in change_config
    work_dir=work_dir)
  File "/home/ederenn/projects/golem/golem/task/taskcomputer.py", line 478, in change_config
    docker_cpu.update_config(DockerCPUConfig(**config_dict))
  File "/home/ederenn/projects/golem/golem/envs/wrappers/__init__.py", line 120, in update_config
    self._env.update_config(config)
  File "/home/ederenn/projects/golem/golem/envs/wrappers/__init__.py", line 120, in update_config
    self._env.update_config(config)
  File "/home/ederenn/projects/golem/golem/envs/docker/cpu.py", line 690, in update_config
    "Config can be updated only when the environment is disabled")
builtins.ValueError: Config can be updated only when the environment is disabled
 ```

**Actual result**:

In interface it seems like it is not possible to resume Golem

## Steps To Reproduce
_Short description of steps to reproduce the behavior:_
e.g.
1. Launch the app 
2. Click on Stop Golem button
3. Switch on "I want to act only as a requestor "
4. Click button Start Golem
5. See error in logs

## Proposed Solution?
_(Optional: What could be a solution for that issue)_

**Comment by etam** [comment] 2020-04-01 08:54
Seems like some unfinished work introduced by #4618

**Comment by etam** [comment] 2020-04-03 13:24
@ederenn could you give me full log? Maybe there's something more required to reproduce it, because I can't.

**Comment by ederenn** [comment] 2020-04-06 14:28
[golem.log.2020-03-17.log](https://github.com/golemfactory/golem/files/4438951/golem.log.2020-03-17.log)
[golem.log.2020-03-30.log](https://github.com/golemfactory/golem/files/4438952/golem.log.2020-03-30.log)
[golem.log.2020-03-31.log](https://github.com/golemfactory/golem/files/4438953/golem.log.2020-03-31.log)
[golem.log.2020-04-01.log](https://github.com/golemfactory/golem/files/4438954/golem.log.2020-04-01.log)

error should be at 31.03

**Comment by etam** [comment] 2020-04-07 10:22
No such error in those logs

**Comment by etam** [comment] 2020-04-07 15:43
I don't know yet where, but a missing step has something to do with a Task API task. Otherwise the "docker cpu environment" is never activated.

**Comment by etam** [comment] 2020-04-10 09:04
I found it!
The important part is to stop and reconfigure golem, while it's computing (i.e. being a provider for) a Task API task.

**Comment by etam** [comment] 2020-05-04 11:35
fixed and merged to b0.23

**Closed as completed by etam** 2020-05-04 11:35 UTC
Labels: bug, P2, 0.23 release
